# yaml to create the secret for secret-s3
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "us-south",
      "access_key": "",
      "endpoint": "s3.us-south.cloud-object-storage.appdomain.cloud",
      "insecure": false,
      "s3_force_path_style": true,
      "secret_key": ""
    }