# yaml to create the secret for secret-s3
apiVersion: v1
kind: Secret
metadata:
  name: s3-auth
stringData:
  service-account.json: |
    {
      "region": "us-south",
      "access_key": "532a8f3c861447ec9dbe6abcfc21b2a7",
      "endpoint": "s3.us-south.cloud-object-storage.appdomain.cloud",
      "insecure": false,
      "s3_force_path_style": true,
      "secret_key": "32ffcb08fbd47d80da2bd7a9089de8038584e5502745df67"
    }

