# create the secret before docker-secret
apiVersion: v1
kind: Pod
metadata:
  name: test-als-all-in-one-pod
spec:
  automountServiceAccountToken: false
  containers:
  - name: test
    command:
    - /usr/local/bin/dockerd-entrypoint.sh
    image: quay.io/alunsin/all_in_one_dind:    resources: {}
    terminationMessagePolicy: FallbackToLog-ppc64le
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 18
  volumes:
  - emptyDir: {}
    name: docker-graph-storage
  - name: secrets
    secret: 
      secretName: docker-secret
status: {}  
