postsubmits:
  florencepascual/webhook-test:
  - name: postsubmit     
    decorate: true
    branches: 
      - master 
    spec:
      containers:
        - image: quay.io/florencepascual/docker_ce_build
          command:
          - /bin/bash
          args:
          - -c
          - |
            bash /usr/local/bin/dockerd-entrypoint.sh &
            echo "Waiting for dockerd to start"
            TIMEOUT=10
            DAEMON="dockerd"
            i=0
            while [ $i -lt $TIMEOUT ] && ! /usr/bin/pgrep $DAEMON
            do
              i=$((i+1))
              sleep 2
            done
            pid=`/usr/bin/pgrep $DAEMON`
            if [ -z "$pid" ]
            then
              echo "$DAEMON did not started after $(($TIMEOUT*2)) seconds"
              exit 1
            else
              echo "Found $DAEMON pid:$pid"
              ps -aef | grep docker | grep -v grep
              sleep 10
              ps -aef
              echo "Launching docker info"
              docker info
              if ! test -d /root/.docker 
              then
                mkdir /root/.docker
                echo "$DOCKER_SECRET_AUTH" > /root/.docker/config.json
              fi
              if grep -Fq "index.docker.io" /root/.docker/config.json
              then
                echo "Docker login"
                docker run hello-world
                docker run --name test alpine
                docker ps -a
                if [ "$(docker ps -a | grep test)" ]
                then
                  echo "Done"
                  ps -e | grep $DAEMON
                  kill -9 $pid
                fi
              fi
            fi
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-root
            mountPath: /var/lib/docker
          env:
            - name: DOCKER_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-token
                  key: .dockerconfigjson
        restartPolicy: Never
        volumes:
        - name: docker-root
          emptyDir: {}
         