postsubmits:
  florencepascual/webhook-test:
  - name: postsubmit     
    decorate: true
    branches: 
      - master 
    spec:
      containers:
        - image: quay.io/florencepascual/docker_ce_build
          command:
          - /bin/bash
          args:
          - -c
          - |
            echo "Executing prow job"
          resources: {}
        restartPolicy: Never

         