periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
      - image: quay.io/powercloud/docker-ce-build
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: DOCKER_SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: .dockerconfigjson
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-auth
                key: access_key
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-auth
                key: secret_key
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
