periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
      - image: quay.io/powercloud/docker-ce-build
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        - name: docker-secret
          mountPath: /etc/docker-secret
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
      - name: docker-secret
        secret: 
          secretName: docker-token
