periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
      - image: quay.io/powercloud/docker-ce-build
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          echo ${S3_ID}:${S3_SECRET} > .passwd-s3fs
          chmod 600 .passwd-s3fs
          mkdir -p /mnt/s3_ppc64le-docker
          s3fs ppc64le-docker /mnt/s3_ppc64le-docker -o url=https://s3.us-south.cloud-object-storage.appdomain.cloud -o passwd_file=/.passwd-s3fs
          ls /mnt/s3_ppc64le-docker
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: DOCKER_SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: .dockerconfigjson
          - name: S3_ID
            valueFrom:
              secretKeyRef:
                name: s3-auth
                key: access_key_id
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-auth
                key: secret_access_key
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
