periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: s3://ppc64le-docker
        path_strategy: explicit
      s3_credentials_secret: s3-auth
    extra_refs:
      - org: ppc64le-cloud
        repo: docker-ce-build
        base_ref: main
        workdir: false
    interval: 24h
    spec:
      containers:
      - image: quay.io/powercloud/docker-ce-build
        workingDir: /workspace
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          echo $ARTIFACTS
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: DOCKER_SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: .dockerconfigjson
          - name: S3_SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: secret-s3
                key: password
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
