periodics:
  - name: docker-all-in-one-test
    #labels:
    #  preset-dind-enabled: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          ls
          echo "Hello World"
          docker 
          echo "Waiting for dockerd to start"
          TIMEOUT=10
          DAEMON="dockerd"
          i=0
          while [ $i -lt $TIMEOUT ] && ! /usr/bin/pgrep $DAEMON
          do
              echo "Number: $i"
              i=$((i+1))
              sleep 2
          done
          docker run alpine
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
