periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 2h
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          if ! test -d /root/.docker 
          then
            echo "No .docker found"
            mkdir /root/.docker
          fi
          if ! test -f /root/.docker/config.json
          then
            echo "No config.json found"
            echo "$SECRET_AUTH" > /root/.docker/config.json
            docker run hello-world
            docker run alpine
            docker ps -a
          fi
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: .dockerconfigjson
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
