periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 2h
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          echo "dockerd started"
          if ! test -d /root/.docker 
          then
            mkdir /root/.docker
            echo "$SECRET_AUTH" > /root/.docker/config.json
          fi
          
          echo "Waiting fo docerkd to start"
          TIMEOUT=10
          DAEMON="dockerd"
          i=0
          while [ $i -lt $TIMEOUT ] && ! /usr/bin/pgrep $DAEMON
          do
            echo "Number: $i"
            i=$((i+1))
            sleep 2
          done
          pid=`/usr/bin/pgrep $DAEMON`
          if [ -z "$pid" ] ; then
            echo "$DAEMON did not started after $(($TIMEOUT*2)) seconds"
            exit 1
          else
            echo "Found $DAEMON pid:$pid"
          fi
          ps -aef | grep docker | grep -v grep
          sleep 10
          ps -aef
          echo "Launching docker info"
          docker info
          
          if grep -Fq "index.docker.io" /root/.docker/config.json
          then
            echo "Docker login"
            docker run hello-world
            docker run alpine
            docker ps -a
          fi
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: .dockerconfigjson
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
