periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 2h
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          if ! grep -Fq "index.docker.io" /root/.docker/config.json
          then
            docker login -u "$SECRET_USERNAME" -p "$SECRET_PASSWORD" 
            docker login -u "$SECRET_USERNAME" -p "$SECRET_PASSWORD"
            docker run hello-world
            docker run alpine
            docker ps -a
          fi
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-secret
                key: password
      restartPolicy: Never
      volumes:
      - name: docker-root
        emptyDir: {}
