# test with secret mounted on volume
# not working with kind, have to manually edit pod.yaml BUT LOGIN NOT WORKING

periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          echo "hello"
          bash /usr/local/bin/dockerd-entrypoint.sh &
          echo "Hello" 
          docker login -u /etc/secrets/username -p /etc/secrets/password
          echo "Docker login" 
          if grep -Fq "index.docker.io" ~/.docker/config.json
          then
            echo "docker was logged in, we will run hello-world"
            docker run hello-world
          else
            docker login -u /etc/secrets/username -p /etc/secrets/password
            echo "Docker login 2"
            docker run hello-world
          fi
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
      - name: secrets
        emptyDir: {}
        
        
        
        
 #replace in the pod.yaml       
  volumes:
  - name: secrets
    secret:
      secretName: docker-secret
      defaultMode: 0500
  volumeMounts:
  - name: secrets
    mountPath: /etc/secrets
    readOnly: true    
    
