periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - "/usr/local/bin/dockerd-entrypoint.sh & ls /etc/secrets & docker login -u /etc/secrets/username -p /etc/secrets/password"
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
      - name: secrets
        emptyDir: {}
        
        
        
        
 #replace in the pod.yaml       
  volumes:
  - name: secrets
    secret:
      secretName: docker-secret
  volumeMounts:
  - name: secrets
    mountPath: /etc/secrets
    readOnly: true        
