periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - wget -o /usr/local/bin/dockerd-entrypoint.sh https://raw.githubusercontent.com/docker-library/docker/master/dockerd-entrypoint.sh
        - |
          cat /usr/local/bin/dockerd-entrypoint.sh
          /usr/local/bin/dockerd-entrypoint.sh
          docker info
          docker run hello-world
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
