periodics:
  - name: docker-all-in-one-test
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - "echo HelloWorld & /usr/local/bin/dockerd-entrypoint.sh & ls /etc/secrets"
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
      - name: secrets
        secret:
          secretName: docker-secret
          defaultMode: 0400
          items:
          - key: username
            path: my-username
              
