# test with environment variables WORKING

periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          echo "hello"
          bash /usr/local/bin/dockerd-entrypoint.sh &
          echo "Hello" 
          docker login -u "$SECRET_USERNAME" -p "$SECRET_PASSWORD" 
          echo "Docker login" 
          if grep -Fq "index.docker.io" ~/.docker/config.json
          then
            echo "docker was logged in, we will run hello-world"
            docker run hello-world
          else
            docker login -u $SECRET_USERNAME -p $SECRET_PASSWORD 
            echo "Docker login 2"
            docker run hello-world
          fi
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-secret
                key: password
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
