# get dockerconfig from variables in secret

periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    always_run: true
    interval: 2m
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          #DOCKER_CFG="/root/.docker/config.json"
          #if ! test -f "$DOCKER_CFG"
          #then
          #  touch "$DOCKER_CFG"
          #  echo "$DOCKER_CFG" created
          #fi
          #if test -f "$DOCKER_CFG"
          #then
          #  if ! grep -Fq "index.docker.io" "$DOCKER_CFG"
          #  then
          cat > /root/.docker/config.json <<EOL
          {
              "auths": {
                  "https://index.docker.io/v1/": {
                      "auth": ${SECRET_AUTH}
                  }
              }
          }
          EOL
            #fi
          #fi
          cat /root/.docker/config.json
          echo "$SECRET_AUTH"
          docker run hello-world
          #docker run alpine
          #docker ps -a
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
        env:
          - name: SECRET_AUTH
            valueFrom:
              secretKeyRef:
                name: docker-cred
                key: .dockerconfigjson
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
